name: Build and Release
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Download Dependencies
        run: go mod download
      - name: Build Executable
        run: go build -o dcgo ./cmd/dcgo
      - name: Archive Executable
        uses: actions/upload-artifact@v2
        with:
          name: dcgo-${{ github.sha }}
          path: ./dcgo
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dcgo-${{ github.sha }}
          path: .
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            Changelog:
            - Add feature 1
            - Fix bug 2
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dcgo
          asset_name: dcgo
          asset_content_type: application/octet-stream
