name: release-build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GOVERSION }}
    - name: Download dependencies
      run: go mod download
    - name: Build-Release
      run: go build -o dcgo ./cmd/dcgo
    - name: Create-Release-Build
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v$(cat go.mod | grep "^module" | awk '{print $2}') # Verwenden Sie die in der go.mod definierte Versionsnummer
        release_name: Release v$(cat go.mod | grep "^module" | awk '{print $2}') # Verwenden Sie die in der go.mod definierte Versionsnummer
        body: Beschreibung des Releases # Optional
        draft: false
        prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dcgo
          asset_name: dcgo
          asset_content_type: application/octet-stream
